# -*- coding: utf-8 -*-
"""PORTAFOLIO_APP.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19b913u-NQqnjqj54Ks0WvdywbXMmNF_R
"""

# Celda 1: instalar librerías necesarias
!pip install yfinance matplotlib seaborn pandas numpy scipy --quiet
# Celda 2: funciones core
import yfinance as yf
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from datetime import datetime

sns.set_style("whitegrid")
plt.rcParams["figure.figsize"] = (10,5)
def download_prices(tickers, start, end, interval='1d'):
    df = yf.download(tickers, start=start, end=end, interval=interval, progress=False)
    # Check if the returned object is a Series or DataFrame
    if isinstance(df, pd.Series):
        df = df.to_frame()
    # Check if 'Adj Close' is a column, otherwise assume the DataFrame itself contains the prices
    if 'Adj Close' in df.columns:
        df = df['Adj Close']
    elif len(tickers) > 1 and all('Adj Close' in col for col in df.columns.levels[0]):
         df = df[[('Adj Close', t) for t in tickers]]
         df.columns = tickers # Flatten the multi-level column index
    return df

# Example usage of download_prices
tickers = ['AAPL', 'MSFT', 'GOOG']
start_date = '2023-01-01'
end_date = '2023-12-31'

stock_prices = download_prices(tickers, start_date, end_date)
display(stock_prices.head())